### ISSUE TITLE
Изучение React

### ISSUE THREAD

**Issue by EgorKudryashov** [timetable-analytics/frontend#2]
Для работы над front-end мы будем использовать фраемфорк React. В нашей команде с ним знаком только Стас, поэтому надо изучить эту технологию перед работой.

**Comment by MenacingDwarf** [comment]
Советую посмотреть эти [уроки ](https://www.youtube.com/watch?v=j942wKiXFu8&list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d) на ютубе (на английском).

Еще есть очень топовый [курс](https://www.udemy.com/course/react-the-complete-guide-incl-redux/), правда платный и тоже на английском, но тем не менее там очень все круто объясняется.
